apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: k8s/overlays/dev
    repoURL: https://github.com/codefresh-contrib/flask-kustomize.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: flask-dev
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
